// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDXN_bquCwL8tacoUaV5wSW-QAIISLdSc',
    appId: '1:679309022789:web:17d6e17186b3daf3bbb52c',
    messagingSenderId: '679309022789',
    projectId: 'carwash-go-a8adc',
    authDomain: 'carwash-go-a8adc.firebaseapp.com',
    storageBucket: 'carwash-go-a8adc.firebasestorage.app',
    measurementId: 'G-45PG88H43M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvIGbOQF8N3MOYk5mo-CLx8I9DzJgulQ',
    appId: '1:679309022789:android:854d9604d69351f1bbb52c',
    messagingSenderId: '679309022789',
    projectId: 'carwash-go-a8adc',
    storageBucket: 'carwash-go-a8adc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5sRaezl_QA29uMmGTJ5F6ShwurOEbM0',
    appId: '1:679309022789:ios:fc77a5c46833dadbbbb52c',
    messagingSenderId: '679309022789',
    projectId: 'carwash-go-a8adc',
    storageBucket: 'carwash-go-a8adc.firebasestorage.app',
    iosBundleId: 'com.noon.carwashGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5sRaezl_QA29uMmGTJ5F6ShwurOEbM0',
    appId: '1:679309022789:ios:fc77a5c46833dadbbbb52c',
    messagingSenderId: '679309022789',
    projectId: 'carwash-go-a8adc',
    storageBucket: 'carwash-go-a8adc.firebasestorage.app',
    iosBundleId: 'com.noon.carwashGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDXN_bquCwL8tacoUaV5wSW-QAIISLdSc',
    appId: '1:679309022789:web:22870dd41c94564fbbb52c',
    messagingSenderId: '679309022789',
    projectId: 'carwash-go-a8adc',
    authDomain: 'carwash-go-a8adc.firebaseapp.com',
    storageBucket: 'carwash-go-a8adc.firebasestorage.app',
    measurementId: 'G-8ZNK4L4898',
  );
}
